// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByFmJQUMI-6QBpo313WRawGQit5UFqHD8',
    appId: '1:50567501343:android:c54f2115550bbe5b06272a',
    messagingSenderId: '50567501343',
    projectId: 'chatapp-833c0',
    storageBucket: 'chatapp-833c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkauyNL05N71C9N4qFy-uA5NeJoWLjSD0',
    appId: '1:50567501343:ios:e8a0c6bd5779fdcb06272a',
    messagingSenderId: '50567501343',
    projectId: 'chatapp-833c0',
    storageBucket: 'chatapp-833c0.appspot.com',
    androidClientId: '50567501343-8dibl8oua61drh8m8l4s7fvfk8sec33s.apps.googleusercontent.com',
    iosClientId: '50567501343-e1tgva2aordkpbv6ge2u45h6ncfa8dla.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkline',
  );
}
